global_params:
  length: 100
  seed: 42
  test_size: 0.2

time_series:
  - base: sine_wave
    num_instances: 50
    params:
      amplitude: 1
      frequency: 0.01
      phase: 0
    transformations:
      - name: constant_offset
        params:
          offset: 2
    disturbances:
      - name: noise
        params:
          noise_std: 1.1

  - base: sine_wave
    num_instances: 50
    params:
      amplitude: 2
      frequency: 1.05
      phase: 0
    disturbances:
      - name: signal_loss
        params:
          start: 30
          end: 40

  - base: constant
    num_instances: 50
    params:
      value: 10
    disturbances:
      - name: noise
        params:
          noise_std: 0.5

preprocessors:
  - name: normalize
    module: preprocessors.normalize
    function: normalize

clustering_algorithms:
  - name: k_means
    module: clustering_algorithms.k_means
    function: k_means_clustering
    params:
      n_clusters: 3

  - name: dbscan
    module: clustering_algorithms.dbscan
    function: dbscan_clustering
    params:
      eps: 1.0
      min_samples: 2

metrics:
  - name: silhouette_score
  - name: adjusted_rand_score
  - name: calinski_harabasz_score
